### ISSUE TITLE
Provide position attribute.

### ISSUE THREAD

**Issue by hemanth** [ragingwind/memory-stats-element#1]
I was planning for the same, it would be nice to have:

``` html
<polymer-memory-stats position="tl"></polymer-memory-stats>
```

`tl` -> Top left, `br` -> Bottom right, so on...

:+1:

**Comment by ragingwind** [comment]
I was thinking that. even attributes name is  also same. But I think It would be better that using css or `style` attributes. It would be supports both options? :)

**Comment by ragingwind** [comment]
I added :) It looks better! :cake:  https://github.com/ragingwind/polymer-memory-stats/commit/a43d0683fabdfe762eaf5bf0e7e38f02f036a3ae

**Comment by hemanth** [comment]
Cool :cake: :+1:
