### ISSUE TITLE
Consider renaming to <memory-stats>

### ISSUE THREAD

**Issue by robdodson** [ragingwind/memory-stats-element#2]
Hey @ragingwind, just wanted to say that it's awesome you created this! I just had the same idea and went to see if anyone had already beaten me to it :smile: 

One suggestion I would make is to consider dropping the `polymer-` prefix and just call it `<memory-stats>`. The team has been discouraging folks from prefix their elements with `polymer-` because a developer shouldn't need to know what your Web Component is built with. It also makes it less to type :)

**Comment by ragingwind** [comment]
Oh I understand it. I will. It's not big deal. I could be changed the element name but Should I need to change the bower package name also? because `memory-stats` and `memory-stats-element` [already has ben taken](http://bower.io/search/?q=memory-stats)

**Comment by ragingwind** [comment]
Renamed https://github.com/ragingwind/polymer-memory-stats/commit/ffd8bae4fc30dc4b616dc7a2ac7f8d62b81953ee

**Comment by robdodson** [comment]
I've given up on bower names. I just do robdodson/x-foo

**Comment by ragingwind** [comment]
Got it. done. thanks for the tip
